### ISSUE TITLE
Prefix in config is not being used to generate link

### ISSUE THREAD

**Issue by yusifk88** [ash-jc-allen/short-url#111]
The source code here is different from  what composer requires which comes with a hardcoded prefix(short) and would not apply the prefix set in the config file.
This makes it impossible to change the prefix via config 

 protected function insertShortURLIntoDatabase(): ShortURL
    {
        return ShortURL::create([
            'destination_url'                => $this->destinationUrl,
            'default_short_url'              => config('app.url').'/short/'.$this->urlKey,
            'url_key'                        => $this->urlKey,
            'single_use'                     => $this->singleUse,
            'track_visits'                   => $this->trackVisits,
            'redirect_status_code'           => $this->redirectStatusCode,
            'track_ip_address'               => $this->trackIPAddress,
            'track_operating_system'         => $this->trackOperatingSystem,
            'track_operating_system_version' => $this->trackOperatingSystemVersion,
            'track_browser'                  => $this->trackBrowser,
            'track_browser_version'          => $this->trackBrowserVersion,
            'track_referer_url'              => $this->trackRefererURL,
            'track_device_type'              => $this->trackDeviceType,
            'activated_at'                   => $this->activateAt,
            'deactivated_at'                 => $this->deactivateAt,
        ]);
    }

**Comment by ash-jc-allen** [comment]
Hi @yusifk88,

Sorry that you're having issues with the package. What version of it are you using? v6.1.0 onwards gives you the ability to change the prefix (https://github.com/ash-jc-allen/short-url/blob/v6.1.0/src/Classes/Builder.php) :)

**Comment by yusifk88** [comment]
^5.2

**Comment by ash-jc-allen** [comment]
Ahh okay, in that case, you'll need to update the package in your application to at least v6.1.0 to use the customisable prefix :)

**Comment by yusifk88** [comment]
Okay, the issue here is composer can't detect that even for an update but I
will manual update it
