### ISSUE TITLE
DataBase Connectivity

### ISSUE THREAD

**Issue by ankitjain091997** [ash-jc-allen/short-url#126]
i want to set database name for migration file but i don't  see any option for set database name.so i tried  like this

i changed file config/short-url.php 
like this :
 
 /*
    |--------------------------------------------------------------------------
    | Connection
    |--------------------------------------------------------------------------
    |
    | Here you may configure the connection information for each server that
    | is used by your application. A default configuration has been added
    | for each back-end shipped with Laravel. You are free to add more.
    |
    |
     */
    'connection' => env('SHORT_URL_CONNECTION', null),

    /*

and also changes - vendor/AshAllenDesign\ShortURL\Models\ShortURL.php  AND  vendor/AshAllenDesign\ShortURL\Models\ShortURLVisit.php 

i added this line in both file

<?php
class ShortURL extends Model
{

protected $connected;

  public function __construct()
    {
        parent::__construct(...func_get_args());
        $this->connection = config('short-url.connection');
    }
}

?>

**Comment by ash-jc-allen** [comment]
Hey! If you make a PR for this, I'd be willing to review it. I'm not sure how often other developers need to use different database connections, but if it's something that a lot of people need to do, I'd be willing to consider merging it 😄

**Comment by ankitjain091997** [comment]
yes, I did create PR and that is title "Database connectivity" , so please see my PR
