### ISSUE TITLE
null prefix causes standard routes to 404

### ISSUE THREAD

**Issue by wing5wong** [ash-jc-allen/short-url#142]
null prefix appears to cause 404 when using non default route.

`Route::get('{shortURLKey}', '\AshAllenDesign\ShortURL\Controllers\ShortURLController');` route defined anywhere in routes file causes all routes to return 404

![image](https://user-images.githubusercontent.com/4406993/187808253-d98d98c5-8e42-481a-b396-42662a43af43.png)

![image](https://user-images.githubusercontent.com/4406993/187808186-cdbf7de3-d023-4555-8bb9-e83646342678.png)

![image](https://user-images.githubusercontent.com/4406993/187808202-70a5b0e3-970d-4f5e-9b17-27e543241d04.png)

any route with any other prefix will work but not basic routes
![image](https://user-images.githubusercontent.com/4406993/187809326-cc422d97-1f37-4b44-a110-e7afbf4ec2e1.png)

see pr #123

**Comment by wing5wong** [comment]
Sorry, seems this is now working. no idea what went on here.

**Comment by ash-jc-allen** [comment]
Hey! That's no problem at all. I'm glad you managed to fix it. Let me know if you run into any more issues 😁
