### ISSUE TITLE
Routing issues with non prefixed routes

### ISSUE THREAD

**Issue by wing5wong** [ash-jc-allen/short-url#143]
Hiya

Have tested this a little further from the issue i posted yesterday.

Reproduce the issue as follows. 

1. `composer create-project laravel/laravel short`
2. `cd short`
3. `composer require ashallendesign/short-url`
4. `php artisan vendor:publish --provider="AshAllenDesign\ShortURL\Providers\ShortURLProvider"`
5. set  ` 'prefix' => null,`
6. `php artisan migrate`
7. configure routes
```php
Route::get('/', function () { // works
    return 'root';
});

Route::get('/basic', function () { // 404
    return 'basic route';
});

Route::middleware([])->group(function () { // works
    Route::get('/grouped', function () {
        return 'grouped route';
    });
});

Route::group(['prefix' => 'nested'], function () { // works
    Route::get('/route', function () {
        return 'a test route';
    });
});
```
8. observe the route `/basic` gives 404

`composer.json`

```
"require": {
        "php": "^8.0.2",
        "ashallendesign/short-url": "^7.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^9.19",
        "laravel/sanctum": "^3.0",
        "laravel/tinker": "^2.7"
    },
```

![image](https://user-images.githubusercontent.com/4406993/188059306-4bb9f6db-ff47-484b-b58f-98bfb281c716.png)

**Comment by ash-jc-allen** [comment]
Hey @wing5wong! Thanks for picking up on this. I agree that there's a slight issue here 😄

From what I can gather, I think it's because the package's route is being registered before registering your `web.php` routes. And if there's no prefix, the URL is just `/{shortURLKey}`. So I think this acts as a catch-all.

I think registering the package's route after the rest of the app's routes in `web.php` (rather than before) would likely solve this, but I can't be sure.

For the time being, are you going to be using short URLs with `null` prefixes? I'm quite surprised that this hasn't already been picked up on.

**Comment by wing5wong** [comment]
Hi ash

also I’m surprised after seeing the existing pr around introducing that functionality. 

The plan was to use no prefix( to keep the urls as short as possible)

Unfortunately I’m not fully understanding how all the parts of packages register yet but maybe by manually specifying the service provider and ignoring the auto discovery is a requirement for this?

If that’s the case it may just need to be documented, but for now I will use the empty middleware group as it gets around the issue as well.

**Comment by LogicSatinn** [comment]
> For the time being, are you going to be using short URLs with `null` prefixes? I'm quite surprised that this hasn't already been picked up on.

I picked up on 'null' prefixes, three months ago. I haven't used the package for some time.... but I'm back to using it and I wanted to try 'null' prefixes, it's raining 404. lol

**Comment by ash-jc-allen** [comment]
@wing5wong I'm releasing my book next week and then after that I should have some free time to add a fix for this.

My idea is to add a new `register_routes` config variable. If it is set to `true` (which it will be by default), the code will continue working as it does now. If it's set to `false`, you'll need to manually register the route. I'm thinking of doing this by adding a `ShortUrl::routes();` method that you can add in your `web.php` (similar to how you register some Laravel auth routes).

@LogicSatinn I'm sorry that it's not working out for you haha! I can't believe I never noticed this when I first added it 🤦‍♂️

@wing5wong and @LogicSatinn - Do you have any thoughts on my approach for the fix? You're using the package more often than I probably am, so you'll have a better idea of how it's being used in the wild. So I'm open for suggestions or feedback 😄

**Comment by LogicSatinn** [comment]
> @wing5wong and @LogicSatinn - Do you have any thoughts on my approach for the fix? You're using the package more often than I probably am, so you'll have a better idea of how it's being used in the wild. So I'm open for suggestions or feedback 😄

I'll do my best to figure out what's going on with that.

**Comment by wing5wong** [comment]
> @wing5wong I'm releasing my book next week and then after that I should have some free time to add a fix for this.
> 
> My idea is to add a new `register_routes` config variable. If it is set to `true` (which it will be by default), the code will continue working as it does now. If it's set to `false`, you'll need to manually register the route. I'm thinking of doing this by adding a `ShortUrl::routes();` method that you can add in your `web.php` (similar to how you register some Laravel auth routes).


Sounds fine to me - and gives 3 options
1. Default routes
2. Manually positioned default routes
3. Custom controller routes

**Comment by ash-jc-allen** [comment]
I've just released a new version of Short URL that should solve this bug: https://github.com/ash-jc-allen/short-url/releases/tag/v7.2.0

You should now be able to disable the default route from being registered by setting the `disable_default_route` to ` false`. You can then manually add the following to your app's route file:

```php
\AshAllenDesign\ShortURL\Facades\ShortURL::routes();
```

I hope this fixes your issue? 😄

**Comment by wing5wong** [comment]
Thanks,
working as expected
