### ISSUE TITLE
Short URL redirect not working

### ISSUE THREAD

**Issue by HeadStudios** [ash-jc-allen/short-url#170]
After installing the package through composer I am able to create shortlinks and also define custom keys and return them from the route - however after copy pasting them into a browser I am unable to redirect. So far I have tried creating a custom route in my routes file as so:

Route::get('/offer/{shortURLKey}', '\AshAllenDesign\ShortURL\Controllers\ShortURLController');

and have also tried adding the routes directly into my route file as so

\AshAllenDesign\ShortURL\Facades\ShortURL::routes();

In the end I am stuck in Chrome with the loading screen and no redirect - any input as to why this could be happening would be much appreciated.

Thank you!

**Comment by HeadStudios** [comment]
Please ignore my previous post - I have discovered the cause of the problem being that I used the destination.com redirect URL in the example which is a URL that doesn't exist.. the package works great!

P.S. Any input on setting the option to automatically overwrite a previous key without generating an error when creating shotcuts would be much apprecaited but other than that this works great!

**Comment by ash-jc-allen** [comment]
Hey! I'm really glad you managed to sort it 😄

For overwriting existing short URLs with the same key, I think this part might be best handled in your application code. Off the top of my head, something like this maybe:

```php
use AshAllenDesign\ShortURL\Models\ShortURL as ShortURLModel;

DB::transaction(function () {
    $key = 'my-key-here';

    ShortURLModel::findByKey('my-key-here')?->delete();

    // Create your new short URL here as usual...
});
```

Of course, this approach might not be suitable for your project, but hopefully it points you in the right direction 😄

**Comment by HeadStudios** [comment]
Thank you for your help and your quick response - as well as the sample code. It is much appreciated.
