### ISSUE TITLE
A short URL with this key already exists.

### ISSUE THREAD

**Issue by HeadStudios** [ash-jc-allen/short-url#172]
I am facing the challenge of creating new short URLs where the key all ready exists - I am receiving the following error:

[2023-01-23 11:08:43] local.ERROR: A short URL with this key already exists. {"userId":1,"exception":"[object] (AshAllenDesign\\ShortURL\\Exceptions\\ShortURLException(code: 0): A short URL with this key already exists. at /home/forge/dev1.rrdevours.monster/vendor/ashallendesign/short-url/src/Classes/Builder.php:546)
[stacktrace]

In my ideal situation if the key all ready exists I would like it to be overwritten with the new key (and all click and related data to be cleansed).

So far I have replaced the checkKeyDoesNotExist(): void function definition in the Builder class from

```
protected function checkKeyDoesNotExist(): void
    {
        if (ShortURL::where('url_key', $this->urlKey)->exists()) {
            throw new ShortURLException('A short URL with this key already exists.');
        }
    }
```

```
 protected function checkKeyDoesNotExist(): void
    {
        if (ShortURL::where('url_key', $this->urlKey)->exists()) {
            ShortURL::where('url_key', $this->urlKey)->delete();
        }
    }
```

However I would prefer not to modify the core - I was wondering if there is a config option that will allow me to achieve what I am after to ensure the behavior I am after is achieved.

Thank you!

**Comment by ash-jc-allen** [comment]
Hey @HeadStudios!

At the moment, there's no config option for this, sorry. If it's something that enough people think might be useful though, it might be something I'd consider in the future.

Off the top of my head, you might be able to do something like this:

```php
$shortUrl = DB::transaction(function(): ShortURL {
    ShortURL::where('url_key', 'YOUR-KEY-HERE')->delete();

    return app(Builder::class)->destinationUrl('http://example.com')
        ->urlKey('YOUR-KEY-HERE')
        ->make();
})
```

I've not run the code above (so it might not work), and I'm not sure if it'd fit your use case. But it could hopefully prevent you from needing to make any changes to the core files 🙂
