### ISSUE TITLE
Manually rerun migrations

### ISSUE THREAD

**Issue by HeadStudios** [ash-jc-allen/short-url#174]
I've recently had an issue where my database was wiped clean, I am attempting to remake the structure as my database backup I have just discovered only contained values and not table structure inserts. 

I am attempting to redo the migrations of the short-url from the vendor folder with this command:

php artisan migrate --path=vendor/ashallendesign/short-url/database/migrations

however I am getting back the notice:

Nothing to migrate

If you have any input on how I can manually rerun the database migrations of your plugin it would be much apprecaited.

Thank you!

**Comment by ash-jc-allen** [comment]
Hey @HeadStudios!

To run the migrations, you'll first need to migrate them to your own `database/migrations` folder by using the `php artisan vendor:publish --provider="AshAllenDesign\ShortURL\Providers\ShortURLProvider" command.

You should then be able to run `php artisan migrate` to run the package's migrations.

I hope this helps? 🙂

**Comment by HeadStudios** [comment]
Thank you for your help - I can confirm running the command you specified has moved the migrations to my database folder - my challenge now is re running those specific migrations when they have been run in the past as my database including its structure was deleted and I am recreating it from scratch using a dump from 2 weeks ago that did not include the structure.

Any input on how I can rerun just the shorturl datbase migrations specifically would be much appreciated - but otherwise I appreciate all your help and I understand this is outside the scope of the plugin and does not reflect any way on the quality of what you have built.

Thank you!

Any

**Comment by HeadStudios** [comment]
As an alternative of helping me match the table structure and not being able to run the import - are you able to send an .sql file with the most recent database structure for the short_urls and short_url_visits tables? I could then simply import the structure and then import my database dump.

For the record below is my dump file:
https://gist.github.com/HeadStudios/5beda1c6c24e06415adbd8d1e5b04ab3

And the import I am attempting to import into that structure:
https://gist.github.com/HeadStudios/713a2096bc34ad4a9b1aa5d6971ab04e

And the error I receive when I try to import the file:
https://share.getcloudapp.com/xQuOJoDn

Any input or help much appreciated.

Thank you!

**Comment by ash-jc-allen** [comment]
Hey @HeadStudios! I'm not 100% sure what's gone wrong with your application, sorry, but I'd imagine that running the migrations that you've published will give you the DB structure you're looking for.

Unfortunately, I'm going to close this issue because I like to keep the issues specific to questions/problems with the package (to make it easier for me to stay on top of, etc.). But I do hope you manage to get it sorted though 🙂
