### ISSUE TITLE
How to Disable Validation?

### ISSUE THREAD

**Issue by hilmihidyt** [ash-jc-allen/short-url#205]
i want to shorten for mailto link, but i got error "The destination URL must begin with http:// or https://", how to fix it?

**Comment by ash-jc-allen** [comment]
Hey @hilmihidyt! At the moment, there's no way to disable the validation or pass a `mailto:` URL as a destination URL, sorry. However, if it's something that enough people think might be useful, I'll definitely consider adding that functionality in the future 🙂
