### ISSUE TITLE
Unable to Update or Create a Short URL When Key Already Exists

### ISSUE THREAD

**Issue by HeadStudios** [ash-jc-allen/short-url#206]
Hi,

I am currently using your package and running into an issue when attempting to create or update a Short URL with a specific key. The error I am receiving is "A short URL with this key already exists."

I have ensured that the method I am using to create or update the Short URL checks for an existing Short URL with the same key, and if one exists, it should update that Short URL instead of attempting to create a new one. Despite this, I am still receiving the error that a Short URL with the key already exists.

The relevant code is as follows:

```php
$builder = new Builder();
try {
    $existingShortURL = ShortURL::where('url_key', $urlKey)->first();

    if ($existingShortURL) {
        // If it does, update the existing one
        $existingShortURL->update([
            'destination_url' => $url,
            'redirect_status_code' => 302
        ]);

        $shortURLObject = $existingShortURL;

        Log::info("Updated short URL for key {$urlKey}: {$shortURLObject->default_short_url}");
    } else {
        // Create a new short URL with a 302 redirect status
        $shortURLObject = $builder->destinationUrl($url)
            ->urlKey($urlKey)
            ->redirectStatusCode(302)
            ->trackVisits()
            ->make();

        Log::info("Generated short URL for key {$urlKey}: {$shortURLObject->default_short_url}");
    }
} catch (\Exception $e) {
    Log::error("Failed to generate or update short URL with key {$urlKey}. Exception: {$e->getMessage()}");

    throw $e; // Re-throw the exception to let the handler deal with it.
}
return $shortURLObject->default_short_url;
```

In an attempt to troubleshoot the issue, I isolated the delete method in a route and it worked as expected:

```php
Route::get('/test', function() {
    $key = 'my-url-key';
    $shortURL = \AshAllenDesign\ShortURL\Models\ShortURL::findByKey($key);

    if ($shortURL) {
        $shortURL->delete();
    }
});
```

This makes me believe the issue lies within the creation or updating process when a Short URL with the same key already exists.

I would appreciate any guidance or assistance you can provide on this issue. Thank you in advance for your help!

**Comment by ash-jc-allen** [comment]
Hey @HeadStudios! I'm sorry to hear that you're having problems with the package.

Thanks for the code snippet! I've just copied it into a fresh Laravel project but I can't seem to reproduce the error you're getting. Would it be possible for you to set up a fresh Laravel app that has this error for me, please? I think that'd make it easier for me to try and track down what might be going wrong 🙂
