### ISSUE TITLE
Customize table structure

### ISSUE THREAD

**Issue by waichoonpopular** [ash-jc-allen/short-url#209]

**Comment by ash-jc-allen** [comment]
Hey! To customise the table structure, you'll need to edit the database migration file that get added to your project's `database/migrations` folder after publishing the package's assets (like shown in this section here: https://github.com/ash-jc-allen/short-url#publish-the-config-and-migrations).

Hopefully this should point you in the right direction? But feel free to ask if you ned anymore help 😄
