### ISSUE TITLE
Set single_use to true has no effect when track_visits is false

### ISSUE THREAD

**Issue by nguyentrongthien** [ash-jc-allen/short-url#22]
Hi, I was reading through your code when I notice that the function handleVisit in Resolver does not make sense.

From what I understand, single_use urls will check the number of visits via the relationship with ShortURLVisit. But if track_visits is set to false, new relationship is never created and the check `($shortURL->single_use && count($shortURL->visits))` will always return false, therefore a supposedly "single_use" url can be used multiple times.

**Comment by ash-jc-allen** [comment]
Hi, thanks for picking up on this; it looks like this is in fact a bug. I'm going to try and get a fix out for this tonight.

**Comment by ash-jc-allen** [comment]
@nguyentrongthien I've just pushed up a bug fix for this issue, so this should be fixed in v1.2.1 which I will release later today.
