### ISSUE TITLE
redirect to url instead of throwing 404

### ISSUE THREAD

**Issue by Saifallak** [ash-jc-allen/short-url#220]
what do you think of that feature?
are you open for PR to do that?

**Comment by ash-jc-allen** [comment]
Hey @Saifallak! Would this be for if a short URL with the given key didn't exist? Or would it be for if the destination URL (that we're redirecting to) doesn't exist? 🙂

**Comment by Saifallak** [comment]
if a short URL with the given key didn't exist

----

i don't have any control over destinations

**Comment by ash-jc-allen** [comment]
I think I'd be open to something like that, yeah! 😄

I don't know if you already have any ideas (which I'm open to), but I'd probably be leaning towards something like letting the developer define the custom behaviour in a service provider and doing something like:

```php
ShortURL::handleMissingUsing(function () {
    // Logic goes here that is run when we the short URL doesn't exist.
});

Feel free to suggest anything else though that you might think would be useful 🙂
