### ISSUE TITLE
outdated v2.7 mobiledetect/mobiledetectlib in jenssegers/agent

### ISSUE THREAD

**Issue by JmRy** [ash-jc-allen/short-url#222]
Hello,

The latest version 2.6 of jenssegers/agent uses an outdated version of mobiledetect/mobiledetectlib (2.7). The latest release of this library does not detect the newest desktop versions of Firefox, Edge, ... It returns true on the isMobile function.

It would be nice to update your library with the 4.8 version of mobiledetect/mobiledetectlib.

Thank you in advance. ;-)

**Comment by ash-jc-allen** [comment]
Hey @JmRy! Sorry that you're having issues with the package. 

I see that you've also opened an issue on the `jenssegers/agent` package's repo too (https://github.com/jenssegers/agent/issues/207). From what I can see, I don't think this is something that I can control on my end, but hopefully, it'll be sorted soon 🙂

**Comment by serbanghita** [comment]
Should be fixed https://github.com/jenssegers/agent/issues/207#issuecomment-1800253853

**Comment by ash-jc-allen** [comment]
Nice one, thank you @serbanghita!

@JmRy I'm going to close this issue with the assumption that this is now working as expected. But if you're still experiencing issues after updating to the latest versions of the dependencies, I'll take a look into this and see if there's a way I can contribute 🙂
