### ISSUE TITLE
Prefix Null Issue

### ISSUE THREAD

**Issue by MaheKarim** [ash-jc-allen/short-url#226]
When I null the prefix value like this , 
```code
'prefix' => null, 
```
My all route showing 404 error. But If use any single prefix It's Okay. After set the prefix value, I cleared cache, composer dump-autoload but nothings happened.

**Comment by ash-jc-allen** [comment]
Hey @MaheKarim! Sorry that you're having issues with the package. This is something I keep meaning to add to the documentation.

If I remember rightly, Laravel loads package routes before application routes, which means you'll have a catch-all route (`/shortURLKey`) registered above all your app routes.

To solve this issue, you can set the `short-url.disable_default_route` config value to `true`. This will prevent the route from being registered automatically.

Then at the bottom of your `routes/web.php` file, you can manually register the package's routes by using:

```php
\AshAllenDesign\ShortURL\Facades\ShortURL::routes();
```

That _should_ get everything working again hopefully. Give me a shout if this doesn't solve the issue though 🙂

**Comment by MaheKarim** [comment]
Sorry To Say This, I followed your instructions But It's Not working. Now I maintain ``` '/s' ``` prefix

**Comment by ash-jc-allen** [comment]
Hmm, that's strange! 🤔 That's the way that I've implemented this in a few different projects and it's always worked for me.

What version of the package are you using?

Would it be possible for you to set up a fresh demo repo that has this issue?

If the default route has been registered and you've declared the package's routes at the bottom of your routes file, it _should_ work, in theory.

Of course, you'll need to make sure you don't have any cached routes, etc.

Let's see if we can dig into this and get it working 😁

**Comment by ash-jc-allen** [comment]
If you can create a demo repo on GitHub that has this bug, that'd be great. I can't reproduce this bug myself, so I can't do much more investigation without it, sorry. And I'd also like to keep all the communication in this thread so that it'll help anyone else in the future that runs into the same issue 😄

**Comment by MaheKarim** [comment]
Okay Okay , Can I Share My Working Repo Link Here ?

**Comment by ash-jc-allen** [comment]
Yeah sure! If it's a fresh Laravel project that has Short URL installed and I can use it to reproduce the bug, that'd be perfect 🙂

**Comment by MaheKarim** [comment]
<img width="492" alt="Screenshot 2023-11-30 at 8 54 27 PM" src="https://github.com/ash-jc-allen/short-url/assets/16819523/e1cf1dd3-05cc-4caf-8a04-fa6ab7b6fcc3">

* Yeah It's Working I add before ``` <?php ``` tag. Though It's Showing on Login / Reg Page. Anyway Thanks @ash-jc-allen <3 .
