### ISSUE TITLE
Tenancy with multi databases

### ISSUE THREAD

**Issue by aeq-dev** [ash-jc-allen/short-url#232]
HI @ash-jc-allen 
Thank you for this awesome package,
I'm using [tenancyforlaravel](https://tenancyforlaravel.com/) package, I've implemented multi-database approach,
So it works fine for central domain example.com, but not for sub-domains foo.example.com, because it checks the code in the central database not tenant's one.
Is there a way to make it working ? How could we check the availability of the short link in each tenant database ?
Thanks.

**Comment by aeq-dev** [comment]
Thanks for your answer :) 
I'll check and try to figure it out 
Can we change config(['short-url.connection' => 'my-custom-tenants-db-connection']) on the fly ?

**Comment by ash-jc-allen** [comment]
Sweet! If you do figure it out, it'd be really cool if you could comment on here just to let other devs know how you managed it 😄

To my knowledge, I think you should be able to change the config on the fly.
