### ISSUE TITLE
Compatibility issue with Laravel 11

### ISSUE THREAD

**Issue by iRaziul** [ash-jc-allen/short-url#245]
I was trying to migrate my existing application to Laravel 11 but while trying to install this package I found it is not compatible yet.

![image](https://github.com/ash-jc-allen/short-url/assets/51883557/da14016a-7e66-4582-8610-dfc096e58c04)

**Comment by ash-jc-allen** [comment]
Hey @iRaziul, thanks for spotting this!

The package is compatible with Laravel 11, but it looks like you've got `nesbot/carbon 3.1.1` installed in your project. But `ashallendesign/short-url` requires `~2.0`. So running this command would have worked (but would have downgraded your `nesbot/carbon` version to `^2.0`):

```text
composer require ashallendesign/short-url -W
```

But I've just released `ashallendesign/short-url v7.10.0` to support `nesbot/carbon ^3.0`. Hopefully that should solve the issue now, if you try and install the dependency as usual (without the `-W` flag) 😄

Release: https://github.com/ash-jc-allen/short-url/releases/tag/v7.10.0

**Comment by iRaziul** [comment]
Thanks ❤️‍🔥
