### ISSUE TITLE
Upgrading to Laravel 11

### ISSUE THREAD

**Issue by colivinggit** [ash-jc-allen/short-url#254]
Hi,

I'm trying to upgrade to Laravel 11, but this issue occurs.
Could you help?

<img width="1226" alt="Screenshot 2024-04-25 at 12 06 16" src="https://github.com/ash-jc-allen/short-url/assets/25136437/b432a745-3e79-4e4a-84c1-ba4d6361de04">

**Comment by ash-jc-allen** [comment]
Hey @colivinggit! Sorry that you're having issues with the package. I'm wondering if this is related to https://github.com/ash-jc-allen/short-url/issues/227?

Are you using Laravel Jetstream at the moment? If not, have you tried running the installation command using the `-W` flag like shown in the error message in your screenshot?

This _might_ work:

```text
composer require ashallendesign/short-url -W
```

I'm actually working on some changes for a new major version of Short URL that will be removing the `jenssegers/agent` package shortly 🙂

**Comment by colivinggit** [comment]
Thanks, that worked!

**Comment by ash-jc-allen** [comment]
Perfect, glad it worked! 😄
