### ISSUE TITLE
Laravel 11 compatibility

### ISSUE THREAD

**Issue by andymitrich** [ash-jc-allen/short-url#283]
Hey, Ash, could add some changes to Installation step, because of Laravel 11 uses different method for registering providers?
To use ShortUrl you should add `AshAllenDesign\ShortURL\Providers\ShortURLProvider::class` to providers.php in bootsrap dir.

**Comment by ash-jc-allen** [comment]
Hey @andymitrich! To my knowledge, if you're using package auto-discovery (which I think is enabled by default), you shouldn't need to manually register the provider yourself 🙂

**Comment by ash-jc-allen** [comment]
I'm going to close this issue, but please give me a shout if you're still running into any problems 🙂
