### ISSUE TITLE
composer install  Error prompt

### ISSUE THREAD

**Issue by gyp719** [ash-jc-allen/short-url#289]
curl error 18 while downloading https://mirrors.cloud.tencent.com/repository/composer/mnabialek/laravel-version/v1.0.7/mnabialek-laravel-version-v1.0.7.zip: transfer closed with 23771 bytes remaining to read

**Comment by ash-jc-allen** [comment]
Hey @gyp719, please can you give some more information about this issue so I can investigate it?

**Comment by gyp719** [comment]
已经解决， 应该是我的网络问题

It has been resolved, it should be my network issue
