### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by carlosjs23** [ash-jc-allen/short-url#34]
Clean install using Laravel 6.1.0, PHP 7.3.14, Fedora 31.

The following error is returned each time I put ``composer install``, or any ``php artisan`` command.
```
ramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-autoload-dump: @php artisan package:discover --ansi

   AshAllenDesign\ShortURL\Exceptions\ValidationException  : The config URL length is not a valid integer.

  at /home/carlos/Dev/ispmanager/vendor/ashallendesign/short-url/src/Classes/Validation.php:36
    32|     {
    33|         $urlLength = config('short-url.key_length');
    34| 
    35|         if (! is_int($urlLength)) {
  > 36|             throw new ValidationException('The config URL length is not a valid integer.');
    37|         }
    38| 
    39|         if ($urlLength < 3) {
    40|             throw new ValidationException('The config URL length must be 3 or above.');

  Exception trace:

  1   AshAllenDesign\ShortURL\Classes\Validation::validateKeyLength()
      /home/carlos/Dev/ispmanager/vendor/ashallendesign/short-url/src/Classes/Validation.php:18

  2   AshAllenDesign\ShortURL\Classes\Validation::validateConfig()
      /home/carlos/Dev/ispmanager/vendor/ashallendesign/short-url/src/Providers/ShortURLProvider.php:48

  Please use the argument -v to see more details.
```

Thanks you.

**Comment by carlosjs23** [comment]
I had to remove all validations then run ``php artisan config:cache`` and the problem is solved, it's something normal?.

**Comment by ash-jc-allen** [comment]
Hi Carlos, sorry to hear that you're having issues with the package.

The main way I can imagine that you got this issue is from caching your config. Seeing as you've added some new config, you'll have had to bust your cached config to able to access the new variables in the ``` short-url.php ``` config.

In a development environment, you'll quite often run into issues if you're caching your config and regularly updating it. To make your life easier I'd advise using ``` cache:clear ``` (unless in a testing or production environment) so that you don't run into any further issues with any other packages in future.

It looks like this is can be closed, but if you're still having issues, let me know :)

**Comment by haakony** [comment]
Just a note here. I also got this after a fresh install. 
I haven't done anything to the config and php artisan config:cache gives the same error.
commenting out the validations fixed the install

**Comment by ash-jc-allen** [comment]
@haakony Sorry to hear that you've had an issue with installing the package. I've tried reproducing this a few times on different machines and I couldn't ever replicate it.

Can you give me any steps to reproduce this, please? If so, I can try and take a look at it to write a bug fix for it.

**Comment by haakony** [comment]
Laravel 7 windows php7.3
Think i might have overstated the "fresh" but here's the composer file.

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "Laravel Auth",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "ashallendesign/short-url": "^3.0",
        "creativeorange/gravatar": "^1.0",
        "doctrine/dbal": "^2.10",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "google/recaptcha": "^1.2",
        "guzzlehttp/guzzle": "^6.3",
        "intervention/image": "^2.5",
        "jaybizzle/laravel-crawler-detect": "^1.2",
        "jeremykenedy/laravel-blocker": "^2.2",
        "jeremykenedy/laravel-exception-notifier": "1.2",
        "jeremykenedy/laravel-https": "^1.1",
        "jeremykenedy/laravel-logger": "^3.2",
        "jeremykenedy/laravel-phpinfo": "^1.2",
        "jeremykenedy/laravel-roles": "^3.0",
        "jeremykenedy/laravel2step": "^1.6",
        "jeremykenedy/uuid": "^3.1",
        "laravel/framework": "^7.0",
        "laravel/helpers": "^1.2",
        "laravel/socialite": "^4.3",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "laravelcollective/html": "^6.1",
        "pusher/pusher-php-server": "^4.1",
        "rap2hpoutre/laravel-log-viewer": "^1.4",
        "socialiteproviders/37signals": "^3.0",
        "socialiteproviders/generators": "^4.6",
        "socialiteproviders/instagram": "^3.0",
        "socialiteproviders/linkedin": "^3.1",
        "socialiteproviders/twitch": "^5.1",
        "socialiteproviders/youtube": "^3.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
    "repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/jeremykenedy/Generators-1.git"
        }
    ],
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   AshAllenDesign\ShortURL\Exceptions\ValidationException

  The config URL length is not a valid integer.

  at C:\wamp64\www\asd\vendor\ashallendesign\short-url\src\Classes\Validation.php:37
    33|     {
    34|         $urlLength = config('short-url.key_length');
    35|
    36|         if (! is_int($urlLength)) {
  > 37|             throw new ValidationException('The config URL length is not a valid integer.');
    38|         }
    39|
    40|         if ($urlLength < 3) {
    41|             throw new ValidationException('The config URL length must be 3 or above.');

  1   C:\wamp64\www\asd\vendor\ashallendesign\short-url\src\Classes\Validation.php:18
      AshAllenDesign\ShortURL\Classes\Validation::validateKeyLength()

  2   C:\wamp64\www\asd\vendor\ashallendesign\short-url\src\Providers\ShortURLProvider.php:48
      AshAllenDesign\ShortURL\Classes\Validation::validateConfig()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```
installed just fine after carlos fix and i just reverted the validation after the install

**Comment by ash-jc-allen** [comment]
@haakony My initial thought is that you might have your config cached before you installed the package? Did you by any chance run ``` php artisan config:cache ``` at any point before trying to install it?

It's difficult to tell what might be causing this, but that's my best guess at the moment. The main thing I would advise would be to make a brand new Laravel project, try to install the package and see if it does the same thing.

**Comment by haakony** [comment]
yes i did run config:cache

**Comment by ash-jc-allen** [comment]
@haakony Ah okay, that's what will have caused your problem. Your config that existed before you installed the library will have been cached. So this meant that when the library's provider ran, it will have found the cached version of the config, rather than the newer version that will also include the 'short-url' config values.

I don't think this is necessarily a problem with the package but more with the fact that you had cached your config. However, I'll have a further look into this at some point and see if I can find a workaround for anyone else in your position.

I hope all this helps? :smile:

**Comment by haakony** [comment]
note that i ran that before running `composer require ashallendesign/short-url`

```
haako@ODIN C:\wamp64\www\asd
$ php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!

haako@ODIN C:\wamp64\www\asd
$ composer require ashallendesign/short-url
Using version ^3.0 for ashallendesign/short-url
./composer.json has been updated
```

**Comment by haakony** [comment]
For me it is installed, looking forward to seeing how i can use it.
But you might get others asking.
Maybe add a note to clear the cache before installing in the readme or something ?

**Comment by ash-jc-allen** [comment]
@haakony Yeah from looking at your command line history, running ``` config:cache ``` before installing the command is what caused it. I'd recommend against using ``` config:cache ``` in a development environment if possible because it usually causes unexpected issues when things are changing all the time. It's intended more for a production environment.

Like I say though, I'll make sure to think up a workaround for this as you're likely to have a similar issue when deploying to a live server.

I hope it comes in handy though!

**Comment by carlosjs23** [comment]
@ash-jc-allen the thing is that after you try to install the package having ran config:cache your app get stuck in the config validation exceptions because the package is running the validations in the providers boot, I think that instead of shooting exceptions in the boot we should display a warning about the "config:cache" so the user can clear the cache.

**Comment by ash-jc-allen** [comment]
@carlosjs23 I agree with that that's the issue and we've already established what the cause is. And I also agree that displaying a warning of some kind could be a potential fix for this.

I'm happy to review any pull requests that anyone would like to make to potentially address this :smile:
