### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by mrosama** [ash-jc-allen/short-url#42]
please mention in requirement  required  php  BC Math or GMP extension.

**Comment by ash-jc-allen** [comment]
Good point, this is something that should probably be mentioned. I'm happy to accept a pull request if you want to make one with the updated docs? :)

**Comment by ash-jc-allen** [comment]
This has now been addressed in the v2.3.1 release (https://github.com/ash-jc-allen/short-url/releases/tag/v2.3.1).
