### ISSUE TITLE
Ability to add custom domain?

### ISSUE THREAD

**Issue by Abhi0725** [ash-jc-allen/short-url#56]
Hi 👋 

Is this possible to add a custom domain?

For e.g: our app_url set in config is https://example.com but we want the short url to be from https://eg.com. Right now the package generates the domain from config's app.url.

Can there be something like set a short domain (optional) and use that to construct the URL?

**Comment by ash-jc-allen** [comment]
Hi @Abhi0725, at the moment it's not possible to add a custom domain straight out of the box. If you'd like to make a pull request though, I'd be happy to take a look at it because I think it'd be a really useful feature! :smile:

**Comment by Abhi0725** [comment]
Sure I will send a pull request.

**Comment by Cyborgmatt** [comment]
Until this is added, in the meantime you can edit web/routes.php and use the following:
`Route::domain(env('SITE_URL'))->group(function () {
    Route::get('/{shortURLKey}', '\AshAllenDesign\ShortURL\Controllers\ShortURLController')->name('short');
});`
Then in your .env file set the variable to the URL you want to use.
`SITE_URL=eg.com`
Now in your blade, when referencing a link you can just use, replace $link->url_key with whatever you call your links loop:
`{{ route('short', [$link->url_key]) }}`
