### ISSUE TITLE
Impossible to set custom route in shortURL make

### ISSUE THREAD

**Issue by paoloveggi** [ash-jc-allen/short-url#57]
Hi mate,
first of all may thanks for this great library, it's very cool!

I have an issue and I can't solve it. I'd like to have a custom route for verifying my generated short URLs, for example:

https://myapp.com/s/urlKey

In documentation I read that I need to disable default routing, so in my config/short-url.php I set:

`disable_default_route = true
`

and in my routes/web.php I added this line:

`Route::get('/s/{shortURLKey}', '\AshAllenDesign\ShortURL\Controllers\ShortURLController')->name('short'); 
`

The problem is that when I generate my short URLs I can't set the /s/ prefix in my default_short_url and in database they are stored with the default /short/ URL part. I think that the problem is in your Builder class, the method is insertShortURLIntoDatabase(). As you can see the array key 'default_short_url' doesn't check if I am using the default routing or not. 

Can you please fix this? I don't want to override the Builder class or method because I don't want to lose compatibility with next versions, in any.

Thank you a lot,
bye.

**Comment by ash-jc-allen** [comment]
Hi @paoloveggi,

Sorry to hear that you're having issues.

If I understand your problem right, it seems like everything is working as intended.

If we look at this example and assume that our app's URL is ``` https://webapp.com```:

```
$shortUrl = $builder->destinationUrl('https://destination.com')->urlKey('custom-key')->make();
``` 

By using the above code, you'd create a new ``` ShortURL ``` in the database that had the ``` default_short_url ``` as ``` https://webapp.com/short/custom-key ```. The default short URL is only intended as the default URL if you are using the controller and route together that come with the package.

If you then wanted to use your route structure, you should be able to go to this URL:

```
 https://webapp.com/s/custom-key
```

I've just tested this locally and it seems to work as expected. Please let me know if you're still having issues and try to provide some screenshots, code examples or stack traces so I can try and help out a bit more :smile:

**Comment by paoloveggi** [comment]
Hello,

ok I understood. In my opinion it would be better if in database you store the real shortURL generated by the make() function, anyway it works and I checked the visited links table and it's ok as well.

Nice work,
thank you.

**Comment by moljac024** [comment]
This sounds broken to me. What good is the `default_short_url ` column? How about we make it instead a `short_url ` column and ask users for a callback function that will generate it given a `custom-key` ?

**Comment by ash-jc-allen** [comment]
@moljac024 This is 100% the intended behaviour and is working as expected. When you generate the short URL, it will populate the ` default_short_url ` so that you can quickly grab the link for the model if you're using the default route and controller provided by the package.

If you're not using the default route and controller, there isn't currently a way to store any custom URLs on the model. If you have any ideas about how you might be able to improve or add to the library, I'd be happy to look at any pull requests.
