### ISSUE TITLE
For custom urls

### ISSUE THREAD

**Issue by Ihabafia** [ash-jc-allen/short-url#59]
Hello,

You added this code Builder.php line 428:

            'default_short_url'              => config('app.url').'/short/'.$this->urlKey,

which I think it will be better if we can have it as:

            'default_short_url'              => config('app.url').'/'.config('short-url.short').$this->urlKey,

and in the short-url.php we can add it there for customization:

    'short' => 'short/',

This way if we need to make the site like https://domain.com/s/{shortURLKey}

all that we need to do is changing the config file to:

    'short' => 's/',

and if we need to make it direct like https://domain.com/{shortURLKey} then will change the config file to:

    'short' => '',

I know that by 'disable_default_route' to true will do the job but I notice that when we create it directly to the db will be faster.

Any thughts?

**Comment by ash-jc-allen** [comment]
Hi @Ihabafia, thanks for coming up with the suggestion. It seems like there are a few people now who are wanting some kind of functionality similar to what you've mentioned above.

As it stands at the moment, the ` default_short_url ` path is intended to be used to point to the default controller and route that comes out of the box with the package.

But maybe having an extra column called ` custom_short_url ` might be worthwhile? That way then, we can use your config suggestion like you mentioned above?

Alternatively, you could create your own ` ShortURL ` model which inherits from the packages ` ShortURL ` model and add an accessor which you could use to get your own custom short URL without needing any database or config changes?

What are your thoughts on those suggestions?

**Comment by Ihabafia** [comment]
Hello,

Your suggestion is differently a good solution, but by just implementing my suggestion you don't even need to modify the db at all, because default_short_url in the db will have https://domain.com/s/code automatically one you added the 'short' => 's/', in the config file.

if you added  'default_short_url'              => config('app.url').'/short/'.$this->urlKey, in the Builder.php

This way all we need to do is modify the config file with 'short' => 's/', or even if we don't want to have anything like have it direct https:://domain.com/code then we just need to make it 'short' => '',

**Comment by Ihabafia** [comment]
By the way thank you for your prompt response.

**Comment by Ihabafia** [comment]
I tried your suggestion by creating my own class and extends the Builder class, the problem was that I have to convert all the variables like
```php
    private $keyGenerator;
    private $destinationUrl = null;
    private $singleUse = false;
    ...
```
from private to protected to be able to run the method from my class:

```php
<?php

namespace App\Services;

use AshAllenDesign\ShortURL\Classes\Builder;
use AshAllenDesign\ShortURL\Models\ShortURL;

class Shorten extends Builder
{
    /**
     * Store the short URL in the database.
     */
    protected function insertShortURLIntoDatabase(): ShortURL
    {
        return ShortURL::create([
            'destination_url' => $this->destinationUrl,
            'default_short_url' => config('app.url').'/'.config('short-url.short').$this->urlKey,
            'url_key' => $this->urlKey,
            'single_use' => $this->singleUse,
            'track_visits' => $this->trackVisits,
            'redirect_status_code' => $this->redirectStatusCode,
            'track_ip_address' => $this->trackIPAddress,
            'track_operating_system' => $this->trackOperatingSystem,
            'track_operating_system_version' => $this->trackOperatingSystemVersion,
            'track_browser' => $this->trackBrowser,
            'track_browser_version' => $this->trackBrowserVersion,
            'track_referer_url' => $this->trackRefererURL,
            'track_device_type' => $this->trackDeviceType,
            'activated_at' => $this->activateAt,
            'deactivated_at' => $this->deactivateAt,
        ]);
    }
}
```

So, by converting the variables in the Builder.php from private to protected means that I am modifying your package which means with any updates all my modifications will be gone and I will start getting errors.

**Comment by ash-jc-allen** [comment]
Hi @Ihabafia, my apologies, I should have explained myself a little bit better. Instead of inheriting from the Builder, I was thinking you could inherit from the ` ShortURL ` model class

I haven't run this code or tested it so I might not work straight away. But something along these lines:

```php
class CustomShortURL extends ShortURL
{
    public function getCustomURLAttribute(): string
    {
        return config('app.url').'/'.config('short-url.short').$this->urlKey,
    }
}
```

By doing that, you could then do something along the lines of ` $shortURL->customURL ` to get your custom URL that you want to specify?

**Comment by Ihabafia** [comment]
Yah, but this way I have to invoke the CustomeShortURL myself by creating a custom controller isn't it?

**Comment by Ihabafia** [comment]
Trust me if you have time to test my suggestion it is going to be changing one line of code in the package, and adding that one line in the config file and that's it 😄

**Comment by ash-jc-allen** [comment]
Sorry @Ihabafia, I don't really want to make any changes to how that column is used in the database as it would break the intended behaviour of that column. That column is intended to act as the default URL for if you want to use the controller and route that come by default with the package.

I'd be happy to maybe review a pull request to add a new column to the database so that you can specify your own custom URL. :smile:

**Comment by Ihabafia** [comment]
Ok, sounds good, thank so much.

**Comment by Shipu** [comment]
Add macro so that any one can write custom function.

**Comment by ash-jc-allen** [comment]
Hi @Shipu, I'm not too sure what you mean sorry. As far as I'm aware, there's not much need for any macros in this package because you could just create your own class that inherits from the Builder class? 🙂

**Comment by Shipu** [comment]
it's totally up to you. i'm just suggesting.
