### ISSUE TITLE
The table is missing indexes

### ISSUE THREAD

**Issue by andrey-helldar** [ash-jc-allen/short-url#64]
**short_urls**:

- `url_key`: [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Classes/Builder.php#L454), [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Classes/KeyGenerator.php#L47), [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Controllers/ShortURLController.php#L31), [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Models/ShortURL.php#L112)
- `destination_url`: [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Models/ShortURL.php#L125)
- `created_by`: [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Classes/KeyGenerator.php#L64) - it's better to write `->latest('id')` so that you don't have to create an index on the `created_at` field.

**short_url_visits**:

- `short_url_id`: [here](https://github.com/ash-jc-allen/short-url/blob/master/src/Models/ShortURL.php#L100)

```php
Schema::table('short_urls', function (Blueprint $table) {
    $table->unique('url_key');
    $table->index('destination_url');
    $table->index('created_by');
});

Schema::table('short_url_visits', function (Blueprint $table) {
    $table->index('short_url_id');
});
```

**Comment by ash-jc-allen** [comment]
Hey @andrey-helldar, thanks for flagging this up. I mainly intended for the package's migrations to only create the structure of the tables so that the dev using the package can have more granular control themselves. Of course, if you wish to add indexes to the tables, you can publish the migrations and add them yourself manually :smile:

**Comment by andrey-helldar** [comment]
It is strange for me to force other developers to make changes to the functionality of the package.

In addition, there are many newbies in our industry who don't even know how indexes work.

That is why I suggested changing the package code.

The indexes I found are critical when searching and must be, but now the responsibility for creating them needs to be shifted to others...

However, good luck!

**Comment by ash-jc-allen** [comment]
I'll do a bit of reading into this and check across other packages as well to see what the convention is for this type of thing. If it's looking like some of the other mainstream packages also add indexes to their migrations, I think it'd be good to get them added.

If you'd like to contribute, feel free to make a PR :smile:

**Comment by andrey-helldar** [comment]
I trust you 😁
