### ISSUE TITLE
Is it possible to add a column to the `short_urls` table?

### ISSUE THREAD

**Issue by mulyosyahidin** [ash-jc-allen/short-url#71]
Hello, thanks for this cool package.

I've been using this package for some time, and now I want to add a new feature to my app, namely titles for URLs, just like in Bitly.

When I went back through the documentation, I didn't find an option for that. Or am I not careful enough?

I'm trying to fork to create the feature, but I'm having a problem where the insertShortURLIntoDatabase() method in the Builder class uses mass assignment to add data, which means, need to add those extra columns to the $fillable property in the model. But until now I couldn't do it.

For now, on the controller I do manual changes using Eloquent. But of course this is very ineffective considering it will cause 2 queries in one action.

Please respond and help, thank you.

**Comment by ash-jc-allen** [comment]
Hey @mulyosyahidin!

I'm glad you like the package and that you've found it useful 😄

I have to admit, I do think that it would be a good idea to add a `name` column for to the `short_urls` table. I never really thought about it before, but I can definitely see the use cases for it.

I don't have much free time at the moment to make any changes to the package, but I'd definitely be open to accepting a pull request if you'd like to make one?
