### ISSUE TITLE
change the path - from config('app.url') to config('short-url.url')

### ISSUE THREAD

**Issue by giladTab** [ash-jc-allen/short-url#88]
Hi 
short-url.
I suggest that the default path that use te app path will use by default the app path, but in case user want to change it ( like i need to do in my case ) it will use what was set in short-url config 

in config file add 
'url' => config('app.url') // this is the default
in case user want to change it will be e.g.
'url'= >'https;//bla.me'

need to change all code to support this new config , but it is very easy to be done 
this  change it important for systems that have basic long url

**Comment by ash-jc-allen** [comment]
Hey! I don't really have any plans at the moment to add this myself.

But if this is something that's wanted by enough people, I might add it in the future. Thanks 😄

**Comment by bbredewold** [comment]
@giladTab see https://github.com/ash-jc-allen/short-url/releases/tag/v7.5.0
