### ISSUE TITLE
Forwarding short url parameters to destination when redirecting

### ISSUE THREAD

**Issue by julienarcin** [ash-jc-allen/short-url#92]
Hello,

I would like to be able to forward and merge the url parameters when redirecting.

I mean, I want to create urls of this type:

https://website.com/short/abc?a=b     =>      https://destination.com/long-url-with-parameters?utm_source=test&a=b

It is currently not working. The parameters (a=b) are deleted when redirecting.

I can implement this functionnality and make a PR.

But first, I would like to know your opinions on which option is the best: 

- Should it be the default behavior ? (forwading parameters)
- Should it be customisable in the config.php file globally ? (forward parameters => true/false)
- Should it be implemented on a per-url basis, in database ?

Thanks !

**Comment by ash-jc-allen** [comment]
Hey @julienarcin, this is quite an interesting one 🤔 

If possible, could you give me an example use case of when you might want to do this?

At their core, the short URLs are just returning a redirect (as you already know). Typically, I wouldn't expect redirects to forward query parameters onto the URL that you are being redirected to. But, maybe there's a use case for them here?

I'm also wondering if adding the parameter forwarding defeats the object of having short URLs? They're intended to be short URLs that would be simple for a human to input themselves. I think that by adding the query params to them, they take away the simplicity of them being user-friendly, short URLs and just end up being typical URLs.

Again though, I'm more than open to suggestions on this depending on the different ways people might be using the package 😄
